# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0002_auto_20171201_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
