# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0006_auto_20171201_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
