# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0007_auto_20171201_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='gender',
        ),
        migrations.AddField(
            model_name='post',
            name='rodzaj',
            field=models.CharField(choices=[('s', 'Śniadanie'), ('o', 'Obiad'), ('d', 'Deser'), ('k', 'Kolacja'), ('i', 'Inne')], default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='profil',
            name='plec',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta')], default='M', max_length=1),
        ),
    ]
