# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0008_auto_20171201_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='obraz',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img'),
            preserve_default=False,
        ),
    ]
