# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0009_post_obraz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='obraz',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
