# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0010_auto_20171201_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='data_ur',
        ),
        migrations.AddField(
            model_name='profil',
            name='wiek',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
