# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serwis', '0011_auto_20171207_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wlasciciel', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(related_name='Lista_Znajomych', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
